name: Terraform build
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory and files (Chekcout the repo)
        uses: actions/checkout@v2

      - name: set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: config AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initializing terraform 
        working-directory: ${{github.workspace}}/terraform
        run: terraform init

      - name: Validating terraform 
        working-directory: ${{github.workspace}}/terraform
        run: terraform validate

      - name: Applying terraform 
        working-directory: ${{github.workspace}}/terraform
        run: terraform apply
          

